print("____________________")
print("|        |          |")
print("|        |          |")
print("|        |          |")
print("|________|          |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("____________________")